"""Init Schema

Revision ID: 7d52237a5a86
Revises: 
Create Date: 2026-05-10 13:43:20.573968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d52237a5a86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_categories_status'), 'categories', ['status'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('percent', 'fixed', name='coupon_type_enum'), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_order', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('applicable_type', sa.Enum('all', 'category', 'product', name='coupon_applicable_type_enum'), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_applicable_type'), 'coupons', ['applicable_type'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index('ix_coupons_code_status_dates', 'coupons', ['code', 'status', 'start_at', 'expired_at'], unique=False)
    op.create_index(op.f('ix_coupons_expired_at'), 'coupons', ['expired_at'], unique=False)
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_index(op.f('ix_coupons_min_order'), 'coupons', ['min_order'], unique=False)
    op.create_index(op.f('ix_coupons_start_at'), 'coupons', ['start_at'], unique=False)
    op.create_index(op.f('ix_coupons_status'), 'coupons', ['status'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_code'), 'payment_methods', ['code'], unique=True)
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_payment_methods_status'), 'payment_methods', ['status'], unique=False)
    op.create_table('shipping_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('estimated_delivery', sa.String(length=100), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_methods_id'), 'shipping_methods', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_methods_status'), 'shipping_methods', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by_id'), 'users', ['referred_by_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affiliate_clicks_code_date', 'affiliate_clicks', ['referral_code', 'created_at'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_created_at'), 'affiliate_clicks', ['created_at'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_id'), 'affiliate_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_ip_address'), 'affiliate_clicks', ['ip_address'], unique=False)
    op.create_index('ix_affiliate_clicks_ip_date', 'affiliate_clicks', ['ip_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_referral_code'), 'affiliate_clicks', ['referral_code'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_referrer_user_id'), 'affiliate_clicks', ['referrer_user_id'], unique=False)
    op.create_index('ix_affiliate_clicks_user_date', 'affiliate_clicks', ['referrer_user_id', 'created_at'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('web', 'zalo', 'facebook', name='chat_source_enum'), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'transferred', name='chat_status_enum'), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_guest_phone'), 'chat_sessions', ['guest_phone'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_last_message_at'), 'chat_sessions', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_source'), 'chat_sessions', ['source'], unique=False)
    op.create_index('ix_chat_sessions_source_status', 'chat_sessions', ['source', 'status'], unique=False)
    op.create_index(op.f('ix_chat_sessions_status'), 'chat_sessions', ['status'], unique=False)
    op.create_index('ix_chat_sessions_status_last_msg', 'chat_sessions', ['status', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_user_last_msg', 'chat_sessions', ['user_id', 'last_message_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'shipping', 'success', 'cancelled', name='order_status_enum'), nullable=True),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', name='payment_status_enum'), nullable=True),
    sa.Column('total_base_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_final', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('shipping_full_address', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('shipping_order_code', sa.String(length=50), nullable=True),
    sa.Column('ghn_status', sa.String(length=50), nullable=True),
    sa.Column('expected_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_methods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_coupon_id'), 'orders', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_expected_delivery_time'), 'orders', ['expected_delivery_time'], unique=False)
    op.create_index(op.f('ix_orders_ghn_status'), 'orders', ['ghn_status'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_orders_payment_method_id'), 'orders', ['payment_method_id'], unique=False)
    op.create_index('ix_orders_payment_status', 'orders', ['payment_status', 'status'], unique=False)
    op.create_index('ix_orders_shipping_ghn', 'orders', ['shipping_order_code', 'ghn_status'], unique=False)
    op.create_index(op.f('ix_orders_shipping_method_id'), 'orders', ['shipping_method_id'], unique=False)
    op.create_index(op.f('ix_orders_shipping_order_code'), 'orders', ['shipping_order_code'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_total_final'), 'orders', ['total_final'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_base_price'), 'products', ['base_price'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_gender'), 'products', ['gender'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_name', sa.String(length=255), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('address_detail', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.create_index('ix_user_addresses_user_default', 'user_addresses', ['user_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('affiliate_commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_total', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('commission_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'cancelled', name='commission_status_enum'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_commissions_approved_at'), 'affiliate_commissions', ['approved_at'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_id'), 'affiliate_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_order_id'), 'affiliate_commissions', ['order_id'], unique=True)
    op.create_index(op.f('ix_affiliate_commissions_paid_at'), 'affiliate_commissions', ['paid_at'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_status'), 'affiliate_commissions', ['status'], unique=False)
    op.create_index('ix_affiliate_commissions_status_approved', 'affiliate_commissions', ['status', 'approved_at'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_user_id'), 'affiliate_commissions', ['user_id'], unique=False)
    op.create_index('ix_affiliate_commissions_user_paid', 'affiliate_commissions', ['user_id', 'paid_at'], unique=False)
    op.create_index('ix_affiliate_commissions_user_status', 'affiliate_commissions', ['user_id', 'status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('user', 'bot', 'admin', name='chat_sender_type_enum'), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('is_handoff_to_admin', sa.Boolean(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_intent'), 'chat_messages', ['intent'], unique=False)
    op.create_index('ix_chat_messages_intent_session', 'chat_messages', ['intent', 'session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_is_handoff_to_admin'), 'chat_messages', ['is_handoff_to_admin'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_type'), 'chat_messages', ['sender_type'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_session_id_asc', 'chat_messages', ['session_id', 'id'], unique=False)
    op.create_index('ix_chat_messages_session_sender', 'chat_messages', ['session_id', 'sender_type'], unique=False)
    op.create_table('coupon_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupon_usages_coupon_date', 'coupon_usages', ['coupon_id', 'used_at'], unique=False)
    op.create_index(op.f('ix_coupon_usages_coupon_id'), 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index('ix_coupon_usages_coupon_user', 'coupon_usages', ['coupon_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_id'), 'coupon_usages', ['id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_order_id'), 'coupon_usages', ['order_id'], unique=True)
    op.create_index(op.f('ix_coupon_usages_used_at'), 'coupon_usages', ['used_at'], unique=False)
    op.create_index(op.f('ix_coupon_usages_user_id'), 'coupon_usages', ['user_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_changed_by'), 'order_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_order_status_history_created_at'), 'order_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.create_index('ix_order_status_history_order_created', 'order_status_history', ['order_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_status_history_status'), 'order_status_history', ['status'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_price'), 'product_variants', ['price'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sale_price'), 'product_variants', ['sale_price'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_index(op.f('ix_product_variants_status'), 'product_variants', ['status'], unique=False)
    op.create_index(op.f('ix_product_variants_stock'), 'product_variants', ['stock'], unique=False)
    op.create_table('affiliate_conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=True),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('attribution_type', sa.Enum('cookie', 'code', 'manual', name='attribution_type_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['commission_id'], ['affiliate_commissions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_conversions_attribution_type'), 'affiliate_conversions', ['attribution_type'], unique=False)
    op.create_index(op.f('ix_affiliate_conversions_commission_id'), 'affiliate_conversions', ['commission_id'], unique=True)
    op.create_index(op.f('ix_affiliate_conversions_created_at'), 'affiliate_conversions', ['created_at'], unique=False)
    op.create_index(op.f('ix_affiliate_conversions_id'), 'affiliate_conversions', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_conversions_order_id'), 'affiliate_conversions', ['order_id'], unique=True)
    op.create_index('ix_affiliate_conversions_referred_date', 'affiliate_conversions', ['referred_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_affiliate_conversions_referred_user_id'), 'affiliate_conversions', ['referred_user_id'], unique=False)
    op.create_index('ix_affiliate_conversions_referrer_date', 'affiliate_conversions', ['referrer_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_affiliate_conversions_referrer_user_id'), 'affiliate_conversions', ['referrer_user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_order_variant', 'order_items', ['order_id', 'variant_id'], unique=False)
    op.create_index(op.f('ix_order_items_sku'), 'order_items', ['sku'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'hidden', name='review_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', 'order_item_id', name='uix_product_reviews_user_product_order')
    )
    op.create_index(op.f('ix_product_reviews_id'), 'product_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_product_reviews_order_item_id'), 'product_reviews', ['order_item_id'], unique=True)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index('ix_product_reviews_product_rating', 'product_reviews', ['product_id', 'rating'], unique=False)
    op.create_index('ix_product_reviews_product_status', 'product_reviews', ['product_id', 'status'], unique=False)
    op.create_index(op.f('ix_product_reviews_rating'), 'product_reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_product_reviews_status'), 'product_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_product_reviews_user_id'), 'product_reviews', ['user_id'], unique=False)
    op.create_index('ix_product_reviews_user_product', 'product_reviews', ['user_id', 'product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_reviews_user_product', table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_user_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_status'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_rating'), table_name='product_reviews')
    op.drop_index('ix_product_reviews_product_status', table_name='product_reviews')
    op.drop_index('ix_product_reviews_product_rating', table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_order_item_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_id'), table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_sku'), table_name='order_items')
    op.drop_index('ix_order_items_order_variant', table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_affiliate_conversions_referrer_user_id'), table_name='affiliate_conversions')
    op.drop_index('ix_affiliate_conversions_referrer_date', table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_referred_user_id'), table_name='affiliate_conversions')
    op.drop_index('ix_affiliate_conversions_referred_date', table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_order_id'), table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_id'), table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_created_at'), table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_commission_id'), table_name='affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_conversions_attribution_type'), table_name='affiliate_conversions')
    op.drop_table('affiliate_conversions')
    op.drop_index(op.f('ix_product_variants_stock'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_status'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sale_price'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_price'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_order_status_history_status'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index('ix_order_status_history_order_created', table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_created_at'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_changed_by'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_coupon_usages_user_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_used_at'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_order_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_id'), table_name='coupon_usages')
    op.drop_index('ix_coupon_usages_coupon_user', table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_coupon_id'), table_name='coupon_usages')
    op.drop_index('ix_coupon_usages_coupon_date', table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index('ix_chat_messages_session_sender', table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_id_asc', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sender_type'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_is_handoff_to_admin'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_intent_session', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_intent'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_affiliate_commissions_user_status', table_name='affiliate_commissions')
    op.drop_index('ix_affiliate_commissions_user_paid', table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_user_id'), table_name='affiliate_commissions')
    op.drop_index('ix_affiliate_commissions_status_approved', table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_status'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_paid_at'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_order_id'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_id'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_approved_at'), table_name='affiliate_commissions')
    op.drop_table('affiliate_commissions')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_index('ix_user_addresses_user_default', table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_gender'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_base_price'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index(op.f('ix_orders_total_final'), table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_order_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_method_id'), table_name='orders')
    op.drop_index('ix_orders_shipping_ghn', table_name='orders')
    op.drop_index('ix_orders_payment_status', table_name='orders')
    op.drop_index(op.f('ix_orders_payment_method_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_ghn_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_expected_delivery_time'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_coupon_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_chat_sessions_user_last_msg', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_status_last_msg', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_status'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_source_status', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_source'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_last_message_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_guest_phone'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_affiliate_clicks_user_date', table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_referrer_user_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_referral_code'), table_name='affiliate_clicks')
    op.drop_index('ix_affiliate_clicks_ip_date', table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_ip_address'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_created_at'), table_name='affiliate_clicks')
    op.drop_index('ix_affiliate_clicks_code_date', table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shipping_methods_status'), table_name='shipping_methods')
    op.drop_index(op.f('ix_shipping_methods_id'), table_name='shipping_methods')
    op.drop_table('shipping_methods')
    op.drop_index(op.f('ix_payment_methods_status'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_code'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_coupons_status'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_start_at'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_min_order'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_expired_at'), table_name='coupons')
    op.drop_index('ix_coupons_code_status_dates', table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_applicable_type'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_categories_status'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
