"""add_unique_constraint_to_coupon_usage

Revision ID: 8e3b0e3c34f3
Revises: j8g2h0e6f7i5
Create Date: 2026-05-20 14:45:47.730048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e3b0e3c34f3'
down_revision: Union[str, Sequence[str], None] = 'j8g2h0e6f7i5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affiliate_commissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_affiliate_links_channel'), 'affiliate_links', ['channel'], unique=False)
    op.create_index(op.f('ix_affiliate_links_created_at'), 'affiliate_links', ['created_at'], unique=False)
    op.drop_index(op.f('ix_coupon_usages_coupon_user'), table_name='coupon_usages')
    op.execute("""
        DELETE FROM coupon_usages current_usage
        USING coupon_usages duplicate_usage
        WHERE current_usage.coupon_id = duplicate_usage.coupon_id
          AND current_usage.user_id = duplicate_usage.user_id
          AND current_usage.user_id IS NOT NULL
          AND current_usage.id > duplicate_usage.id
    """)
    op.create_unique_constraint('uq_coupon_usages_coupon_user', 'coupon_usages', ['coupon_id', 'user_id'])
    op.create_index(op.f('ix_newsletter_subscriptions_unsubscribed_at'), 'newsletter_subscriptions', ['unsubscribed_at'], unique=False)
    op.create_index(op.f('ix_orders_coupon_code'), 'orders', ['coupon_code'], unique=False)
    op.alter_column('withdrawal_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'paid', name='withdrawal_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::withdrawal_status_enum"))
    op.alter_column('withdrawal_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_withdrawal_requests_created_at'), 'withdrawal_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_processed_at'), 'withdrawal_requests', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_requests_processed_at'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_created_at'), table_name='withdrawal_requests')
    op.alter_column('withdrawal_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('withdrawal_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'paid', name='withdrawal_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::withdrawal_status_enum"))
    op.drop_index(op.f('ix_orders_coupon_code'), table_name='orders')
    op.drop_index(op.f('ix_newsletter_subscriptions_unsubscribed_at'), table_name='newsletter_subscriptions')
    op.drop_constraint('uq_coupon_usages_coupon_user', 'coupon_usages', type_='unique')
    op.create_index(op.f('ix_coupon_usages_coupon_user'), 'coupon_usages', ['coupon_id', 'user_id'], unique=False)
    op.drop_index(op.f('ix_affiliate_links_created_at'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_channel'), table_name='affiliate_links')
    op.alter_column('affiliate_commissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
