"""add_slug_to_product

Revision ID: d65e698ce2c7
Revises: 7d52237a5a86
Create Date: 2026-05-10 14:14:35.263543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65e698ce2c7'
down_revision: Union[str, Sequence[str], None] = '7d52237a5a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.add_column('products', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_column('products', 'slug')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status', 'status'], unique=False)
    # ### end Alembic commands ###
